name: deep-action-prop-gen
dependencies:
- backports_abc=0.4=py27_0
- bokeh=0.11.0=py27_1
- cairo=1.12.18=6
- cycler=0.9.0=py27_0
- cython=0.23.4=py27_0
- decorator=4.0.6=py27_0
- ffmpeg=2.2.4=0
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- futures=3.0.3=py27_0
- h5py=2.5.0=np110py27_4
- hdf5=1.8.15.1=2
- ipykernel=4.2.2=py27_0
- ipython=4.0.3=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=4.1.1=py27_0
- jbig=2.1=0
- jinja2=2.8=py27_0
- joblib=0.8.4=py27_0
- jpeg=8d=0
- jsonschema=2.4.0=py27_0
- jupyter=1.0.0=py27_1
- jupyter_client=4.1.1=py27_0
- jupyter_console=4.1.0=py27_0
- jupyter_core=4.0.6=py27_0
- libgfortran=1.0=0
- libpng=1.6.17=0
- libsodium=1.0.3=0
- libtiff=4.0.6=1
- libxml2=2.9.2=0
- markupsafe=0.23=py27_0
- matplotlib=1.5.0=np110py27_0
- mistune=0.7.1=py27_0
- natsort=4.0.3=py27_0
- nbconvert=4.1.0=py27_0
- nbformat=4.0.1=py27_0
- networkx=1.10=py27_0
- nose=1.3.7=py27_0
- notebook=4.1.0=py27_0
- numpy=1.10.2=py27_0
- openblas=0.2.14=3
- opencv=2.4.10=np110py27_1
- openssl=1.0.2e=0
- pandas=0.17.1=np110py27_0
- path.py=8.1.2=py27_1
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pillow=3.0.0=py27_1
- pip=8.0.1=py27_0
- pixman=0.32.6=0
- protobuf=2.6.1=py27_1
- ptyprocess=0.5=py27_0
- py=1.4.31=py27_0
- py2cairo=1.10.0=py27_2
- pygments=2.0.2=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_1
- pytest=2.8.5=py27_0
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- python-gflags=2.0=py27_0
- pytz=2015.7=py27_0
- pyyaml=3.11=py27_1
- pyzmq=15.2.0=py27_0
- qt=4.8.7=1
- qtconsole=4.1.1=py27_0
- readline=6.2=2
- requests=2.9.1=py27_0
- scikit-image=0.11.3=np110py27_0
- scikit-learn=0.17=np110py27_1
- scipy=0.16.1=np110py27_0
- setuptools=19.4=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.9.2=0
- ssl_match_hostname=3.4.0.2=py27_0
- terminado=0.5=py27_1
- tk=8.5.18=0
- tornado=4.3=py27_0
- traitlets=4.1.0=py27_0
- wheel=0.26.0=py27_1
- x264=20131217=2
- xz=5.0.5=0
- yaml=0.1.6=0
- yasm=1.2.0=0
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - hickle==1.4.0
  - ipdb==0.8.1
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-console==4.1.0
  - jupyter-core==4.0.6
  - leveldb==0.193

